server:
  port: 8001
###################  spring配置  ###################
spring:
  profiles:
    active: dev

  ##########################################################
  ###################  开发环境的profile  ###################
  ##########################################################
  datasource:
    url: jdbc:mysql://192.168.1.118:3306/flowable-test?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Lzx@123456

#flowable:
    ##  #关闭定时任务JOB
    ##  async-executor-activate: false

###################  日志配置  ###################
logging:
  level.root: info
  level.com.flowable: info
  path: logs/
  file: demo01-info.log

---
logging:
  level.root: warn
  path: logs/
  file: demo01-warn.log